plugins {
    id 'com.android.application'
}

android {
    namespace 'com.ifcompressores.jarvis'
    compileSdk 36

    defaultConfig {
        applicationId 'com.ifcompressores.jarvis'
        minSdk 26
        targetSdk 36
        versionCode 6
        versionName '0.6.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packaging {
        jniLibs {
            useLegacyPackaging = true
        }
    }
}

dependencies {
    implementation 'androidx.webkit:webkit:1.14.0'
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.core:core:1.17.0'
}
